create table task (
        id integer generated by default as identity,
        is_completed BOOLEAN DEFAULT false,
        due_date timestamp(6),
        title varchar(100) not null,
        task_description varchar(255),
        primary key (id)
    )